---
language: rust
dist: trusty
sudo: false

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
    - libssl-dev

matrix:
  include:
  - rust: nightly
  - rust: stable

before_script:
  - cargo clean

script:
  # Build without unstable flag
  - cargo build

  # Build the test executables in a separate step, since Tarpaulin
  # will not fail on test compile errors.
  - cargo build --tests

  # Run tests
  - RUST_TEST_THREADS=1 cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email:
    on_success: never
