[package]
name = "docdoc"
version = "0.1.0"
authors = ["Marc Addeo <marcaddeo@gmail.com>"]

[dependencies]
pulldown-cmark = { version = "0.0.11", default-features = false }
tera = "0.10"
serde = "1.0"
serde_derive = "1.0"
docopt = "0.8"
serde_yaml = "0.7"
fs_extra = "1.0.0"
comrak = "0.2.3"
